# Generated by Django 5.1.2 on 2025-01-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='car_license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_license',
        ),
    ]
