# Generated by Django 5.1.2 on 2025-01-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user_profile_email_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='cars/')),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback')], max_length=10)),
                ('transmission', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=10)),
                ('brand', models.CharField(choices=[('proton', 'Proton'), ('perodua', 'Perodua'), ('honda', 'Honda'), ('toyota', 'Toyota')], max_length=10)),
                ('seats', models.IntegerField(choices=[(5, '5 seats'), (7, '7 seats')])),
                ('price_range', models.CharField(choices=[('0-200', '0-200'), ('200>', '200>')], max_length=10)),
            ],
        ),
    ]
