# Generated by Django 5.1.2 on 2025-01-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
    ]
