# Generated by Django 5.1.2 on 2025-01-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('pickup_date', models.CharField(blank=True, max_length=100)),
                ('pickup_time', models.CharField(blank=True, max_length=100)),
                ('return_date', models.CharField(blank=True, max_length=100)),
                ('return_time', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='price_range',
            field=models.CharField(choices=[('0-200', '0-200'), ('>200', '>200')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(choices=[(5, '5'), (7, '7')]),
        ),
    ]
