# Generated by Django 5.1.2 on 2025-01-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_rental_phone_number_alter_rental_pickup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
